
package GUI;

import experiments.Experiment;
import experiments.ExperimentNew;
import experiments.Fish;
import experiments.FishGroup;
import experiments.FishGroupNew;
import experiments.FishNew;
import experiments.ImageAnalysis;
import experiments.ImageAnalysisNew;
import experiments.Measurement;
import experiments.MeasurementNew;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.time.Instant;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import tools.AutomaticCellFinder;
import tools.CellAnalysator;
import tools.CellFinder;
import tools.ContrastAdjuster;
import tools.Cropper;
import tools.ExperimentExporter;
import tools.MontageCreator;
import tools.OptiFlattener;

/**
 *
 * @author janlu
 */
public class MainMenuGUI extends javax.swing.JFrame {
    private Experiment experiment;
    private OptiFlattener flattener;
    private int ongoingOperation = 0;
    private Thread workThread;
            
    /**
     * Creates new form CellFinderGUI
     */
    public MainMenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        experimentInformationPanel = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        injectionDateLabel = new javax.swing.JLabel();
        groupCountLabel = new javax.swing.JLabel();
        fishCountLabel = new javax.swing.JLabel();
        confocalCountLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JLabel();
        injectionDateField = new javax.swing.JLabel();
        groupCountField = new javax.swing.JLabel();
        fishCountField = new javax.swing.JLabel();
        confocalCountField = new javax.swing.JLabel();
        newExperimentButton = new javax.swing.JButton();
        openExperimentButton = new javax.swing.JButton();
        actionPanel = new javax.swing.JPanel();
        refreshButton = new javax.swing.JButton();
        flattenImagesButton = new javax.swing.JButton();
        traceFishButton = new javax.swing.JButton();
        countCellsButton = new javax.swing.JButton();
        adjustContrastButton = new javax.swing.JButton();
        makeMontageButton = new javax.swing.JButton();
        SegmentCellsButton = new javax.swing.JButton();
        analyzeCellsButton = new javax.swing.JButton();
        cellChannelSpinner = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        experimentTree = new javax.swing.JTree();
        progressBar = new javax.swing.JProgressBar();
        taskLable = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        workingOnFileNumber = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        totalFileNumber = new javax.swing.JLabel();
        fileNameField = new javax.swing.JLabel();
        taskField = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        abortButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lastSaveField = new javax.swing.JLabel();
        fileProgressBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        experimentInformationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel.setText("Experiment name:");

        injectionDateLabel.setText("Injection date:");

        groupCountLabel.setText("Groups:");

        fishCountLabel.setText("Fish:");

        confocalCountLabel.setText("Confocal images:");

        nameField.setText("None");

        injectionDateField.setText("None");

        groupCountField.setText("0");

        fishCountField.setText("0");

        confocalCountField.setText("0");

        newExperimentButton.setText("New Experiment");
        newExperimentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newExperimentButtonActionPerformed(evt);
            }
        });

        openExperimentButton.setText("Open Experiment");
        openExperimentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openExperimentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout experimentInformationPanelLayout = new javax.swing.GroupLayout(experimentInformationPanel);
        experimentInformationPanel.setLayout(experimentInformationPanelLayout);
        experimentInformationPanelLayout.setHorizontalGroup(
            experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experimentInformationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addComponent(injectionDateLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(experimentInformationPanelLayout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(fishCountLabel))
                        .addComponent(groupCountLabel))
                    .addComponent(confocalCountLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(confocalCountField)
                    .addComponent(nameField)
                    .addComponent(injectionDateField)
                    .addComponent(fishCountField)
                    .addComponent(groupCountField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 230, Short.MAX_VALUE)
                .addGroup(experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newExperimentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openExperimentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        experimentInformationPanelLayout.setVerticalGroup(
            experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(experimentInformationPanelLayout.createSequentialGroup()
                .addGroup(experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(experimentInformationPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabel)
                            .addComponent(nameField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(injectionDateLabel)
                            .addComponent(injectionDateField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(groupCountLabel)
                            .addComponent(groupCountField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fishCountLabel)
                            .addComponent(fishCountField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(experimentInformationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(confocalCountLabel)
                            .addComponent(confocalCountField)))
                    .addGroup(experimentInformationPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(newExperimentButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openExperimentButton)))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        actionPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        refreshButton.setText("Refresh");
        refreshButton.setEnabled(false);
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        flattenImagesButton.setText("Flatten images");
        flattenImagesButton.setEnabled(false);
        flattenImagesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flattenImagesButtonActionPerformed(evt);
            }
        });

        traceFishButton.setText("Trace fish");
        traceFishButton.setEnabled(false);
        traceFishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                traceFishButtonActionPerformed(evt);
            }
        });

        countCellsButton.setText("Manual cell counting");
        countCellsButton.setEnabled(false);
        countCellsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countCellsButtonActionPerformed(evt);
            }
        });

        adjustContrastButton.setText("Adjust contrast");
        adjustContrastButton.setEnabled(false);
        adjustContrastButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adjustContrastButtonActionPerformed(evt);
            }
        });

        makeMontageButton.setText("Make montage");
        makeMontageButton.setEnabled(false);
        makeMontageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeMontageButtonActionPerformed(evt);
            }
        });

        SegmentCellsButton.setText("Cell segmentation");
        SegmentCellsButton.setEnabled(false);
        SegmentCellsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SegmentCellsButtonActionPerformed(evt);
            }
        });

        analyzeCellsButton.setText("Analyze objects");
        analyzeCellsButton.setEnabled(false);
        analyzeCellsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                analyzeCellsButtonActionPerformed(evt);
            }
        });

        cellChannelSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        cellChannelSpinner.setEnabled(false);

        jLabel5.setText("Cell channel:");

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(adjustContrastButton, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(makeMontageButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(flattenImagesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(traceFishButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SegmentCellsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(countCellsButton)
                    .addComponent(analyzeCellsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cellChannelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton)
                    .addComponent(countCellsButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flattenImagesButton)
                    .addComponent(SegmentCellsButton)
                    .addComponent(jLabel5)
                    .addComponent(cellChannelSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(analyzeCellsButton)
                    .addComponent(traceFishButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adjustContrastButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(makeMontageButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        experimentTree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        experimentTree.setRootVisible(false);
        experimentTree.setShowsRootHandles(true);
        experimentTree.setVisibleRowCount(40);
        jScrollPane1.setViewportView(experimentTree);

        taskLable.setText("Task:");

        jLabel1.setText("File name:");

        jLabel2.setText("File");

        workingOnFileNumber.setText("0");

        jLabel4.setText("of");

        totalFileNumber.setText("0");

        fileNameField.setText("None");

        taskField.setText("None");

        saveButton.setText("Save");
        saveButton.setEnabled(false);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        abortButton.setText("Abort");
        abortButton.setEnabled(false);
        abortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abortButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Last save:");

        lastSaveField.setText("Never");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(taskLable)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(taskField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(workingOnFileNumber)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(totalFileNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fileNameField)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(experimentInformationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(actionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progressBar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addComponent(fileProgressBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lastSaveField)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(abortButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(saveButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(experimentInformationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taskLable)
                            .addComponent(taskField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(fileNameField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(workingOnFileNumber)
                            .addComponent(jLabel4)
                            .addComponent(totalFileNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fileProgressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(abortButton)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lastSaveField)
                                .addComponent(jLabel3)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        updateExperiment();
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void newExperimentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newExperimentButtonActionPerformed
        NewExperimentGUI newExperiment = new NewExperimentGUI(this, true);
        newExperiment.setLocationRelativeTo(this);
        newExperiment.setVisible(true);
        Experiment tempExperiment = newExperiment.getExperiment();
        if (tempExperiment == null ) return;
        this.experiment = tempExperiment;
        updateExperiment();
        flattenImagesButton.setEnabled(true);
        adjustContrastButton.setEnabled(true);
        traceFishButton.setEnabled(true);
        countCellsButton.setEnabled(true);
        saveButton.setEnabled(true);
        makeMontageButton.setEnabled(true);
        SegmentCellsButton.setEnabled(true);
        cellChannelSpinner.setEnabled(true);
    }//GEN-LAST:event_newExperimentButtonActionPerformed

    private void openExperimentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openExperimentButtonActionPerformed
        final JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                FileInputStream fileInStream = new FileInputStream(fileChooser.getSelectedFile());
                ObjectInputStream objectInStream = new ObjectInputStream(fileInStream);
                experiment = (Experiment) objectInStream.readObject();
                objectInStream.close();
                fileInStream.close();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainMenuGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainMenuGUI.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(MainMenuGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
            updateExperiment();
            flattenImagesButton.setEnabled(true);
            adjustContrastButton.setEnabled(true);
            traceFishButton.setEnabled(true);
            countCellsButton.setEnabled(true);
            saveButton.setEnabled(true);
            analyzeCellsButton.setEnabled(true);
            makeMontageButton.setEnabled(true);
            SegmentCellsButton.setEnabled(true);
            cellChannelSpinner.setEnabled(true);
        }
    }//GEN-LAST:event_openExperimentButtonActionPerformed

    private void flattenImagesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flattenImagesButtonActionPerformed
        FlattenerGUI flattenerGUI = new FlattenerGUI(this, true);
        flattenerGUI.setLocationRelativeTo(this);
        flattenerGUI.setVisible(true);
        int tileSize = flattenerGUI.getTileSize();
        int projectionMethod = flattenerGUI.getProjectionMethod();
        if((tileSize == 0) || (projectionMethod == 0)) return;
        flattener = new OptiFlattener(experiment, this, tileSize, projectionMethod);
        workThread = new Thread(flattener);
        workThread.start();
    }//GEN-LAST:event_flattenImagesButtonActionPerformed

    private void abortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abortButtonActionPerformed
        taskField.setText("Interrupting, wait for current file to finish");
        workThread.interrupt();
    }//GEN-LAST:event_abortButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        ExperimentNew newExperiment = new ExperimentNew(experiment.getName(), experiment.getConfocalDirectory(), experiment.getTimeOfFertilization(), experiment.getTimeOfInjection());
        newExperiment.setFishCount(experiment.getFishCount());
        newExperiment.setGroupCount(experiment.getGroupCount());
        newExperiment.setImageCount(experiment.getImageCount());
        ArrayList<FishGroupNew> newGroups = new ArrayList();
        for(FishGroup group : experiment.getGroups()) {
            FishGroupNew newGroup = new FishGroupNew(group.getGroupName());
            newGroup.setParent(newExperiment);
            ArrayList<FishNew> newFishList = new ArrayList();            
                    
            for(Fish fish : group.getFishList()) {
                FishNew newFish = new FishNew(fish.getName(), newGroup);
                ArrayList<MeasurementNew> newMeasurementList= new ArrayList();
                
                for(Measurement measurement : fish.getMeasurements()) {
                    MeasurementNew newMeasurement = new MeasurementNew(measurement.getConfocalFile(), newFish);
                    newMeasurement.setFishROI(measurement.getFishROI());
                    ArrayList<ImageAnalysisNew> newAnalysisList = new ArrayList();
                    
                    for(ImageAnalysis analysis : measurement.getAnalyses()){
                        ImageAnalysisNew newAnalysis = new ImageAnalysisNew(analysis.getAnalysisType(), analysis.getAnalysisFiles(), analysis.getChannelIDs(), analysis.getAnalysisTime(), newMeasurement);
                        newAnalysisList.add(newAnalysis);
                    }
                    newMeasurement.setAnalyses(newAnalysisList);
                    newMeasurementList.add(newMeasurement);
                }
                newFish.setMeasurements(newMeasurementList);
                newFishList.add(newFish);
            }
            newGroup.setFishList(newFishList);
            newGroups.add(newGroup);
        }
        newExperiment.setGroups(newGroups);
        
        ExperimentExporter.exportExperiment(newExperiment);
        //saveExperiment();
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void adjustContrastButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adjustContrastButtonActionPerformed
        AdjustChannelsGUI contrastGUI = new AdjustChannelsGUI(this, true, experiment);
        contrastGUI.setLocationRelativeTo(this);
        contrastGUI.setVisible(true);
        ImageAnalysis controllAnalysis = contrastGUI.getAnalysis();
        if (controllAnalysis == null ) return;
        ContrastAdjuster contrastAdjust = new ContrastAdjuster(experiment, controllAnalysis);
        workThread = new Thread(contrastAdjust);
        workThread.start();
    }//GEN-LAST:event_adjustContrastButtonActionPerformed

    private void traceFishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_traceFishButtonActionPerformed
        Cropper cropper = new Cropper(experiment, this);
        workThread = new Thread(cropper);
        workThread.start();
    }//GEN-LAST:event_traceFishButtonActionPerformed

    private void countCellsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countCellsButtonActionPerformed
        CellFinder finder = new CellFinder(experiment, this);
        workThread = new Thread(finder);
        workThread.start();
    }//GEN-LAST:event_countCellsButtonActionPerformed

    private void makeMontageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeMontageButtonActionPerformed
        MontageCreator montageCreator = new MontageCreator(experiment, this);
        workThread = new Thread(montageCreator);
        workThread.start();
    }//GEN-LAST:event_makeMontageButtonActionPerformed

    private void SegmentCellsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SegmentCellsButtonActionPerformed
        int cellChannel = (int) cellChannelSpinner.getValue();
        cellChannel--;
        AutomaticCellFinder cellFinder = new AutomaticCellFinder(experiment, this, cellChannel);
        workThread = new Thread(cellFinder);
        workThread.start();
    }//GEN-LAST:event_SegmentCellsButtonActionPerformed

    private void analyzeCellsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzeCellsButtonActionPerformed
        CellAnalysisGUI cellAnalysisGUI = new CellAnalysisGUI(this, true, experiment);
        cellAnalysisGUI.setLocationRelativeTo(this);
        cellAnalysisGUI.setVisible(true);
    }//GEN-LAST:event_analyzeCellsButtonActionPerformed

    private void refreshExperimentTree() {
        
        if (experiment == null) {
            DefaultMutableTreeNode root = new DefaultMutableTreeNode("No experiment selected");
            experimentTree.setModel(new DefaultTreeModel(root));
            return;
        }
        DefaultMutableTreeNode root = new DefaultMutableTreeNode("Experiment: " + experiment.getName());
        if (experiment.isUsesGroups()) {
            ArrayList<FishGroup> groupList = experiment.getGroups();
            for (FishGroup fishGroup : groupList) {
                DefaultMutableTreeNode groupNode = new DefaultMutableTreeNode("Group: " + fishGroup.getGroupName());
                ArrayList<Fish> fishList = fishGroup.getFishList();
                for (Fish fish : fishList) {
                    DefaultMutableTreeNode fishNode = new DefaultMutableTreeNode("Fish: " + fish.getName());
                    ArrayList<Measurement> measurementList = fish.getMeasurements();
                    for (Measurement measurement : measurementList) {
                        DefaultMutableTreeNode measurementNode = new DefaultMutableTreeNode("Measurement: " + measurement.getFileName());
                        ArrayList<ImageAnalysis> analysisList = measurement.getAnalyses();
                        for (ImageAnalysis analysis : analysisList) {
                            DefaultMutableTreeNode analysisNode = new DefaultMutableTreeNode("Analysis: " + analysis.getAnalysisName());
                            measurementNode.add(analysisNode);
                        }
                        fishNode.add(measurementNode);
                    }
                    groupNode.add(fishNode);
                }
                root.add(groupNode);
            } 
        }
        else {
            String[] fishList = experiment.getFishNames();
            for (String fishName : fishList) {
                DefaultMutableTreeNode fish = new DefaultMutableTreeNode("Fish: " + fishName);
                String[] acquisitionList = experiment.getFish(fishName).getMeasurementNames();
                for (String acquisitionName : acquisitionList) {
                    DefaultMutableTreeNode measurement = new DefaultMutableTreeNode("Measurement: " + acquisitionName);
                    fish.add(measurement);
                }
                root.add(fish);
            }  
        }
        experimentTree.setModel(new DefaultTreeModel(root));
    }
    
    public void setProgress(String fileName, int workingOn, int total) {
        workingOnFileNumber.setText(workingOn + "");
        totalFileNumber.setText(total + "");
        fileNameField.setText(fileName);
        progressBar.setMaximum(total);
        progressBar.setValue(workingOn);
    }
    public void setFileProgress(int progress, int total) {
        setFileProgress(null, progress, total);
    }
    public void setFileProgress(String task, int progress, int total) {
        fileProgressBar.setMaximum(total);
        fileProgressBar.setValue(progress);
        fileProgressBar.setString(task);
        fileProgressBar.setStringPainted(true);
    }
    public void setTask(String task, int taskID) {
        System.out.println("In message");
        taskField.setText(task);
        System.out.println("Task: " + taskField.getText());
        ongoingOperation = taskID;
        newExperimentButton.setEnabled(false);
        openExperimentButton.setEnabled(false);
        flattenImagesButton.setEnabled(false);
        adjustContrastButton.setEnabled(false);
        traceFishButton.setEnabled(false);
        countCellsButton.setEnabled(false);
        abortButton.setEnabled(true);
        saveButton.setEnabled(false);
        refreshButton.setEnabled(false);
        makeMontageButton.setEnabled(false);
        SegmentCellsButton.setEnabled(false);
        cellChannelSpinner.setEnabled(false);
    }
    public void finishTask(String taskCompleted) {
        ongoingOperation = 0;
        taskField.setText("None - " + taskCompleted + " finished");
        fileNameField.setText("None");
        totalFileNumber.setText(0 + "");
        workingOnFileNumber.setText(0 + "");
        progressBar.setValue(0);
        newExperimentButton.setEnabled(true);
        openExperimentButton.setEnabled(true);
        flattenImagesButton.setEnabled(true);
        adjustContrastButton.setEnabled(true);
        traceFishButton.setEnabled(true);
        countCellsButton.setEnabled(true);
        abortButton.setEnabled(false);
        saveButton.setEnabled(true);
        refreshButton.setEnabled(true);
        makeMontageButton.setEnabled(true);
        SegmentCellsButton.setEnabled(true);
        cellChannelSpinner.setEnabled(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SegmentCellsButton;
    private javax.swing.JButton abortButton;
    private javax.swing.JPanel actionPanel;
    private javax.swing.JButton adjustContrastButton;
    private javax.swing.JButton analyzeCellsButton;
    private javax.swing.JSpinner cellChannelSpinner;
    private javax.swing.JLabel confocalCountField;
    private javax.swing.JLabel confocalCountLabel;
    private javax.swing.JButton countCellsButton;
    private javax.swing.JPanel experimentInformationPanel;
    private javax.swing.JTree experimentTree;
    private javax.swing.JLabel fileNameField;
    private javax.swing.JProgressBar fileProgressBar;
    private javax.swing.JLabel fishCountField;
    private javax.swing.JLabel fishCountLabel;
    private javax.swing.JButton flattenImagesButton;
    private javax.swing.JLabel groupCountField;
    private javax.swing.JLabel groupCountLabel;
    private javax.swing.JLabel injectionDateField;
    private javax.swing.JLabel injectionDateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lastSaveField;
    private javax.swing.JButton makeMontageButton;
    private javax.swing.JLabel nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton newExperimentButton;
    private javax.swing.JButton openExperimentButton;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel taskField;
    private javax.swing.JLabel taskLable;
    private javax.swing.JLabel totalFileNumber;
    private javax.swing.JButton traceFishButton;
    private javax.swing.JLabel workingOnFileNumber;
    // End of variables declaration//GEN-END:variables

    private void updateExperiment() {
        if (experiment == null) return;
        nameField.setText(experiment.getName());
        injectionDateField.setText(experiment.getTimeOfInjection().toString());
        groupCountField.setText(String.valueOf(experiment.getGroupCount()));
        fishCountField.setText(String.valueOf(experiment.getFishCount()));
        confocalCountField.setText(String.valueOf(experiment.getImageCount()));        
        refreshExperimentTree();
    }

    public void saveExperiment() {
        if (experiment == null) return;
        try {
            FileOutputStream fileOutStream 
                    = new FileOutputStream(experiment.getConfocalDirectory() 
                    + "\\" + experiment.getName() 
                    + ".exp");
            ObjectOutputStream objectOutStream = new ObjectOutputStream(fileOutStream);
            objectOutStream.writeObject(experiment);
            objectOutStream.close();
            fileOutStream.close();
            lastSaveField.setText(Instant.now().toString());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(MainMenuGUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(MainMenuGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        updateExperiment();
    }

    
}
